"""fix polymorphic link

Revision ID: 02f1ec29946d
Revises: 3cbef84c86d3
Create Date: 2026-06-19 14:50:51.722899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f1ec29946d'
down_revision: Union[str, Sequence[str], None] = '3cbef84c86d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_lines', sa.Column('article_type', sa.String(length=50), nullable=False))
    op.add_column('invoice_lines', sa.Column('article_id', sa.Integer(), nullable=False))
    op.add_column('invoice_lines', sa.Column('origin_type', sa.String(length=20), nullable=False))
    op.add_column('invoice_lines', sa.Column('origin_id', sa.Integer(), nullable=False))
    op.drop_column('invoice_lines', 'source_type')
    op.drop_column('invoice_lines', 'source_id')
    op.create_unique_constraint(None, 'invoices', ['invoice_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='unique')
    op.add_column('invoice_lines', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('invoice_lines', sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('invoice_lines', 'origin_id')
    op.drop_column('invoice_lines', 'origin_type')
    op.drop_column('invoice_lines', 'article_id')
    op.drop_column('invoice_lines', 'article_type')
    # ### end Alembic commands ###
