"""add constraints sale

Revision ID: d60eeb8cf1ab
Revises: ae980673d874
Create Date: 2026-06-19 15:24:40.108471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60eeb8cf1ab'
down_revision: Union[str, Sequence[str], None] = 'ae980673d874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 🟢 1. CONTRAINTES POUR LA TABLE "sale_lines_bikes"
    op.create_check_constraint(
        "ck_sale_line_bike_quantity_positive",
        "sale_lines_bikes",
         sa.text("quantity_sold > 0")
    )

    # 🟢 2. CONTRAINTE POUR LA TABLE "sale_lines_parts"
    op.create_check_constraint(
        "ck_sale_line_part_quantity_positive",
        "sale_lines_parts",
         sa.text("quantity_sold > 0")
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 🔴 SUPPRESSION DES CONTRAINTES DE "sale_lines_bikes"
    op.drop_constraint("ck_sale_line_bike_quantity_positive", "sale_lines_bikes", type_="check")

    # 🔴 SUPPRESSION DE LA CONTRAINTE DE "sale_lines_parts"
    op.drop_constraint("ck_sale_line_part_quantity_positive", "sale_lines_parts", type_="check")

    # ### end Alembic commands ###
