"""add constraints invoice.py

Revision ID: dc966dac6b68
Revises: d60eeb8cf1ab
Create Date: 2026-06-19 15:32:36.392215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc966dac6b68'
down_revision: Union[str, Sequence[str], None] = 'd60eeb8cf1ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Validation de la quantité positive
    op.create_check_constraint(
        "ck_invoice_line_quantity_positive",
        "invoice_lines",
        sa.text("quantity > 0")
    )
    
    # 2. Validation du type d'article (Vélo ou Pièce détachée)
    op.create_check_constraint(
        "ck_invoice_line_article_type_valid",
        "invoice_lines",
        sa.text("article_type IN ('inventory_bike', 'spare_part')")
    )

    # 3. Validation de l'origine de la transaction (Vente ou Réparation)
    op.create_check_constraint(
        "ck_invoice_line_origin_type_valid",
        "invoice_lines",
        sa.text("origin_type IN ('sale', 'repair_order')")
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Suppression des trois contraintes (l'option type_="check" est requise pour PostgreSQL)
    op.drop_constraint("ck_invoice_line_quantity_positive", "invoice_lines", type_="check")
    op.drop_constraint("ck_invoice_line_article_type_valid", "invoice_lines", type_="check")
    op.drop_constraint("ck_invoice_line_origin_type_valid", "invoice_lines", type_="check")

    # ### end Alembic commands ###
