"""add constraint inventory_bike and spare_part

Revision ID: e6c47b632114
Revises: 02f1ec29946d
Create Date: 2026-06-19 15:08:54.063866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c47b632114'
down_revision: Union[str, Sequence[str], None] = '02f1ec29946d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Contraintes pour la table inventory_bikes
    op.create_check_constraint(
        "ck_inventory_bike_stock_non_negative",
        "inventory_bikes",
        "quantity_in_stock >= 0"
    )
    op.create_check_constraint(
        "ck_inventory_bike_purchase_price_non_negative",
        "inventory_bikes",
        "purchase_price_net >= 0"
    )
    op.create_check_constraint(
        "ck_inventory_bike_retail_price_non_negative",
        "inventory_bikes",
        "retail_price_net >= 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_inventory_bike_stock_non_negative", "inventory_bikes")
    op.drop_constraint("ck_inventory_bike_purchase_price_non_negative", "inventory_bikes")
    op.drop_constraint("ck_inventory_bike_retail_price_non_negative", "inventory_bikes")
    # ### end Alembic commands ###
